#!/bin/bash

OS_NAME=`uname`

if [[ $OS_NAME != 'Darwin' ]] && [[ $OS_NAME != 'Linux' ]];
	then
		for i in `seq 1 10`;
		do
			echo "Meow" >> $i.txt
		done
		exit
fi

case $1 in
  -help | -h)
    echo "Welcome to the help page of marquee. Sorry but i can't help you.."
    exit
  ;;
  -list-fonts | -lf)
    convert -list font | grep Font: | sed 's/^.*: //g'
    exit
  ;;
esac

if [[ $# == 0 ]]
    then
     echo "Insufficient nr of arguments!"
     exit
fi

# The text
GIF_TEXT="$1"
shift

# Color of the text is set to black by default
TEXT_COLOR="black"

TEXT_COLOR_FLASH="black"
TEXT_COLOR_FLASH_ALT="black"

# 4:th argument is the background color
BG_COLOR="white"

BG_COLOR_FLASH="white"
BG_COLOR_FLASH_ALT="white"

FILE_NAME="out.gif"

DELAY=0

FONT="Arial"

OPTIMIZATION=0
OPT_ON=false

RAINBOW_BG=false
RAINBOW_C=false

SPEED=20

BLUR=false
BLUR_LEVEL=0x0

SWIRL=false
SWIRL_DEGREE=0

FLASH_TEXT=false
FLASH_BG=false

# Check flags
while [ "$1" ]
do
	case $1 in
		-name | -n)
		        shift
			FILE_NAME="$1"
		;;
		-text-color | -c)
			shift
			TEXT_COLOR=$1
		;;
		-background-color | -b)
			shift
			BG_COLOR=$1
		;;
		-delay | -d)
			shift
			DELAY=$1
		;;
		-font | -t)
			shift
			FONT="$1"
		;;
		-optimize | -o)
			shift
			OPTIMIZATION=$1
			OPT_ON=true
		;;
		-speed | -s)
			shift
			SPEED=$1
                ;;
                -gaussian-blur | -gs)
                        shift
                        BLUR=true
                        BLUR_LEVEL=$1
                ;;
                -swirl | -s)
                        shift
                        SWIRL=true
                        SWIRL_DEGREE=$1
                ;;
		*)
			echo "What is this? --> $1" >&2
			exit 1
		;;
	esac
	shift
done

RGB_RGX="rgb\(((25[0-5]|2[0-4][0-9]|[01][0-9][0-9]|[1-9]?[0-9]),){2}(25[0-5]|2[0-4][0-9]|[01][0-9][0-9]|[1-9]?[0-9])\)"
RGBA_RGX="rgba\(((25[0-5]|2[0-4][0-9]|[01][0-9][0-9]|[1-9]?[0-9])\,){3}(1\.0|0?\.[0-9]+|0|1)\)"
COLORS_RGX="(white|black|red|green|blue|yellow|purple|orange|cyan|indigo|magenta|pink|brown|gray)"
ALL_COLORS_RGX="(${RGB_RGX}|${RGBA_RGX}|${COLORS_RGX})"
FLASHING_RGX=" *flash\( *${ALL_COLORS_RGX} *, *${ALL_COLORS_RGX} *\) *"

FLOAT_RGX="[0-9]*\.?[0-9]+"

if ! [[ "$SPEED" =~ ^[0-9]+$ ]]
	then
		echo "Illegal argument: $SPEED, must be positive" >&2
		exit 1
fi

if ! [[ "$TEXT_COLOR" =~ ^($ALL_COLORS_RGX|$FLASHING_RGX|rainbow)$ ]]
	then
		echo "Illegal argument: $TEXT_COLOR" >&2
		exit 1
fi

if ! [[ "$BG_COLOR" =~ ^($ALL_COLORS_RGX|$FLASHING_RGX|rainbow|none)$ ]]
	then
		echo "Illegal argument: $BG_COLOR" >&2
		exit 1
fi

if ! [[ "$OPTIMIZATION" =~ ^(0|1|2|3)$ ]]
	then
		echo "Illegal argument: $OPTIMIZATION" >&2
		exit 1
fi

if ! [[ "$BLUR_LEVEL" =~ ^[0-9]+x[0-9]+$ ]]
   then
     echo "Illegal argument: $BLUR_LEVEL" >&2
     exit 1
fi

if ! [[ "$SWIRL_DEGREE" =~ ^$FLOAT_RGX$ ]]
then
  echo "Illegal argument: $SWIRL_DEGREE" >&2
  exit 1
fi

# Create a temporary dir for marquee to put temporary files
if ! [ -d "/tmp/marquee" ];
	then
		mkdir /tmp/marquee
fi

if [[ "$BG_COLOR" =~ "rainbow" ]]
   then
     RAINBOW_BG=true
     BG_COLOR="hsl(0,100%,50%)"
fi

if [[ "$TEXT_COLOR" =~ "rainbow" ]]
   then
     RAINBOW_C=true
     TEXT_COLOR="hsl(0,100%,50%)"
fi

if [[ "$TEXT_COLOR" =~ $FLASHING_RGX ]]
   then
     COLORS=$(sed 's/(//g; s/)//g; s/flash//g; s/\s+//g' <<< $TEXT_COLOR)
     IFS=','
     read -a COLORS <<< "$COLORS"
     TEXT_COLOR_FLASH=${COLORS[0]}
     TEXT_COLOR_FLASH_ALT=${COLORS[1]}
     TEXT_COLOR=${COLORS[0]}
     FLASH_TEXT=true
     unset IFS
fi

if [[ "$BG_COLOR" =~ $FLASHING_RGX ]]
   then
     COLORS=$(sed 's/(//g; s/)//g; s/flash//g; s/\s+//g' <<< $BG_COLOR)
     IFS=','
     read -a COLORS <<< "$COLORS"
     BG_COLOR_FLASH=${COLORS[0]}
     BG_COLOR_FLASH_ALT=${COLORS[1]}
     BG_COLOR=${COLORS[0]}
     FLASH_BG=true
     unset IFS
fi

# Add 3 Images together, a center with the text and two padding images that only contain the background color
create_image() {
  convert -size 128x128 xc:$BG_COLOR /tmp/marquee/padding.png
  convert -background $BG_COLOR -fill $TEXT_COLOR -font "$FONT" -size x128 label:"$GIF_TEXT" /tmp/marquee/center.png
  convert /tmp/marquee/padding.png /tmp/marquee/center.png /tmp/marquee/padding.png +append /tmp/marquee/res.png
  rm /tmp/marquee/padding.png
  rm /tmp/marquee/center.png
}


get_width() {
  create_image
  echo "$(convert /tmp/marquee/res.png -ping -format "%w\n" info:)"
}

create_image

# Get the width of the image
IMG_WIDTH=$(get_width)
FRAME_OFFSET=($(seq 0 $SPEED $((IMG_WIDTH-128))))
NR_OF_FRAMES=${#FRAME_OFFSET[@]}

IMG_INDEX=0

for i in "${FRAME_OFFSET[@]}";
do
  if $RAINBOW_BG;
     then
       HUE=$(( (360 / $NR_OF_FRAMES) * $IMG_INDEX ))
       BG_COLOR="hsl("$HUE",100%,50%)"
  fi
  if $RAINBOW_C
     then
       HUE=$(( (180 + ((360 / $NR_OF_FRAMES) * $IMG_INDEX) ) % 260 ))
       TEXT_COLOR="hsl("$HUE",100%,50%)"
  fi
  
  if $FLASH_TEXT
     then
       if (( $IMG_INDEX % 8 < 4 )); then
         TEXT_COLOR=$TEXT_COLOR_FLASH
         create_image
       else
         TEXT_COLOR=$TEXT_COLOR_FLASH_ALT
         create_image
       fi
  fi
  if $FLASH_BG
     then
       if (( $IMG_INDEX % 8 < 4 )); then
         BG_COLOR=$BG_COLOR_FLASH
       else
         BG_COLOR=$BG_COLOR_FLASH_ALT
       fi
  fi
  if $RAINBOW_BG || $RAINBOW_BG || $FLASH_TEXT || $FLASH_BG
     then
       create_image
  fi
  convert -crop 128x128+$i+0 +repage /tmp/marquee/res.png /tmp/marquee/$IMG_INDEX.png
  IMG_TMP_NAME="/tmp/marquee/"$IMG_INDEX
  IMG_TMP_NAME=$IMG_TMP_NAME".png "
  GIF_FILES=$GIF_FILES$IMG_TMP_NAME
  ((IMG_INDEX++))
done

# Create the gif
convert -dispose Background -colors 8 -delay $DELAY $GIF_FILES $FILE_NAME

if $BLUR
then
  convert $FILE_NAME -blur $BLUR_LEVEL $FILE_NAME
fi

if $SWIRL
then
  convert $FILE_NAME -swirl 360 $FILE_NAME
fi

# Optimize the file size of the gif with gifsicle
if $OPT_ON ; then
	gifsicle -O$OPTIMIZATION $FILE_NAME -o $FILE_NAME
fi

# Clear temporary files
#rm /tmp/marquee/*
